### ISSUE TITLE
Issues part is not opened for xz repository

### ISSUE THREAD

**Issue by Neustradamus** [xz-mirror/xz-mirror#5]
Dear @xz-mirror team, @tukaani-project team, @Larhzu, @JiaT75, @simnalamburt,

Issues part is not opened for xz repository, can you add it?

And there are missing releases here:
- https://github.com/xz-mirror/xz/releases

You can see tags:
- https://github.com/xz-mirror/xz/tags

In more, @Larhzu, @JiaT75: Can you add you in public here: https://github.com/orgs/xz-mirror/people?

In more too, I think it is possible to harmonize only one place for code with a redirection.

Thanks in advance.

**Comment by JiaT75** [comment]
Hello @Neustradamus!

Larzhu and I are not affiliated with this repository or the organization so we do not have the ability to make any of these changes. My understanding is that this organization provided a GitHub mirror long before we officially moved the XZ Utils repository to GitHub. We maintain a [mirror](https://git.tukaani.org/) but that is mainly for people who had been pulling from the old official repositories.

This organization is obviously free to continue mirroring however they wish but the most up to date version of XZ Utils will always be [here](https://github.com/tukaani-project/xz).

**Comment by simnalamburt** [comment]
Wow hang on I didn’t know that xz project has been officially migrated to GitHub.

Yes, long time ago (like at 2014~2015) XZ project was only hosted at git.tukaani.org and it didn’t supported HTTPS protocol so people behind internet traffic sensorship were hard to clone or download xz source code. And server uptime was unstable so I decided to create a mirror for xz.

Now, if canonical repository of xz is at GitHub, there’s no big point maintaining this mirror except keeping backward compatibility. I’ll mark this mirror as deprecated and recommend users to see official one instead.

**Comment by Neustradamus** [comment]
@simnalamburt: There is a solution to be perfect!

It is possible to give ownership of this organization to @Larhzu, @JiaT75?

I have a solution to have only one repository and a redirection https://github.com/xz-mirror/xz -> https://github.com/tukaani-project/xz.

Only @Larhzu, @JiaT75 can do steps.

**Comment by simnalamburt** [comment]
Adding two people as collaborators of [xz-mirror/xz](https://github.com/xz-mirror/xz) is not difficult, but as far as I know, there is no way to make an already existing repository a redirection of another already existing repository.

Can you tell me what you are trying to do?

**Comment by Neustradamus** [comment]
@simnalamburt: Not collaborators, owners.

xz-mirror/xz is a real mirror, it can be remove by one new owner (@Larhzu, @JiaT75) and temporary transfer of tukaani-project/xz into xz-mirror organization and transfer again into the good place -> tukaani-project.
It takes few minutes to do all steps.

All redirections will exist, all people will go at the good place :)

**Comment by Neustradamus** [comment]
Some examples:
- https://github.com/asciimoo/searx -> https://github.com/searx/searx
- https://github.com/boothj5/profanity -> https://github.com/profanity-im/profanity
- https://github.com/nerzhul/ocsms -> https://github.com/nextcloud/ocsms
- https://github.com/tigaseinc/tigase-server -> https://github.com/tigase/tigase-server

**Comment by simnalamburt** [comment]
Oh that’s clever. I’ll add @Larhzu, @JiaT75 to xz-mirror organization if they agree to do that.

**Comment by JiaT75** [comment]
After discussing with Larzhu, we agreed that we do not wish to set up this redirection. While it is a clever idea, the redirections mentioned by @Neustradamus were all projects that moved the official repository from one namespace to another. This is different than redirecting an unaffiliated mirror to the official repository.

We announced XZ Utils moved to GitHub many months ago through our public mailing list and project website, so there is not much room for users to complain they were not notified with enough time to update their links :)

Again, @simnalamburt is free to maintain this mirror how he pleases, but we do not feel comfortable transferring the official XZ Utils repository to the xz-mirror organization, even for a few minutes. We appreciate the update to xz-mirror/xz's About section notifying users about the location of the official repository and encourage either deprecating this mirror or continuing to keep it up to date. This is important to be sure everyone is using an updated version of our project and makes it easier for us to maintain things.

So this may inconvenience a few users who need to update their links but that is the best solution from our perspective.

**Comment by Neustradamus** [comment]
The solution is to remove xz-mirror/xz repository

People mix...

You can see here, there is the same problem with this official https://github.com/doublecmd/doublecmd and unofficial https://github.com/double-commander/doublecmd.

**Comment by simnalamburt** [comment]
I've marked https://github.com/xz-mirror/xz as archived, and put links pointing to the official repository in several places. I hope this helps.

<img width="906" alt="image" src="https://github.com/xz-mirror/xz-mirror/assets/4435445/02b67d58-2da4-49ea-8cd5-0210d4abc458">

<img width="963" alt="image" src="https://github.com/xz-mirror/xz-mirror/assets/4435445/053803d4-38e2-45b2-b7cf-69f0ec2aa21e">

**Comment by JiaT75** [comment]
Thanks @simnalamburt. I think that is sufficient. And thanks for maintaining this mirror for people who could not otherwise access the source code for XZ Utils. Your efforts are appreciated.
